<a href="https://colab.research.google.com/github/JaswanthJavangula/ML_Practise/blob/main/1ML%20JAshu/KNN/KNN_KNC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [50]:
from sklearn.datasets import make_classification

X,y = make_classification(
    n_samples = 2500,n_features=5,n_redundant=1,n_classes=2,random_state=123
    )

In [51]:
X

array([[-1.26206297,  0.44508838, -1.21438686, -0.12484183,  0.57343172],
       [ 1.01299482, -0.44042802,  0.72937552, -0.22549973, -0.84438552],
       [ 1.01186645, -0.06990277,  2.77107729,  1.43363171,  0.86539867],
       ...,
       [ 0.40461964, -0.6640115 ,  0.16360986,  3.01097082, -2.59131081],
       [ 1.28806489, -0.42465785,  1.20420704,  0.00627641, -0.44854869],
       [-1.24571846,  0.23804514,  0.54548513, -1.5063553 , -0.36351413]])

In [52]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y, test_size =0.33,random_state=42)

In [53]:
from sklearn.neighbors import KNeighborsClassifier
KNC=  KNeighborsClassifier(n_neighbors=4,algorithm="auto")
KNC.fit(X_train,y_train)
y_pred = KNC.predict(X_test)

In [54]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
accuracy_score(y_test,y_pred)

              precision    recall  f1-score   support

           0       0.84      0.92      0.88       405
           1       0.92      0.83      0.87       420

    accuracy                           0.87       825
   macro avg       0.88      0.87      0.87       825
weighted avg       0.88      0.87      0.87       825

[[373  32]
 [ 72 348]]


0.8739393939393939

grid search cv

In [56]:
from sklearn.model_selection import GridSearchCV

param_grid ={
    "n_neighbors" : [1,2,3,4,6,7,8,9]
}
grid = GridSearchCV(KNC, param_grid,cv=5,verbose=1,n_jobs=-1)
grid.fit(X_train,y_train)
y_pred_grid = grid.predict(X_test)
print(grid.best_params_)

print(classification_report(y_test,y_pred_grid))
print(confusion_matrix(y_test,y_pred_grid))
accuracy_score(y_test,y_pred_grid)

Fitting 5 folds for each of 8 candidates, totalling 40 fits
{'n_neighbors': 7}
              precision    recall  f1-score   support

           0       0.89      0.88      0.88       405
           1       0.88      0.89      0.89       420

    accuracy                           0.88       825
   macro avg       0.88      0.88      0.88       825
weighted avg       0.88      0.88      0.88       825

[[355  50]
 [ 45 375]]


0.8848484848484849